services:
  server:
    container_name: server
    image: server
    build: ./requirements/server
    ports:
      - 443:443
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - public-transcendence-network
      - private-transcendence-network
    volumes:
      - ./requirements/server:/app

  backend:
    container_name: backend
    image: backend
    build: ./requirements/backend
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - private-transcendence-network
    volumes:
      - ./requirements/backend:/app
      - /app/node_modules # Prevents overwriting dependencies

  database:
    container_name: database
    image: database
    build: ./requirements/database
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - private-transcendence-network
    volumes:
      - database_data:/var/lib/sqlite

  blockchain:
    container_name: blockchain
    image: blockchain
    build: ./requirements/blockchain
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - private-transcendence-network
    volumes:
      - blockchain_data:/app/blockchain

volumes:
  database_data:
    driver: local
    driver_opts:
      type: none
      device: ${DATA_PATH}/database
      o: bind
  blockchain_data:
    driver: local
    driver_opts:
      type: none
      device: ${DATA_PATH}/blockchain
      o: bind

networks:
  public-transcendence-network:
    name: public-transcendence-network
    driver: bridge
  private-transcendence-network:
    name: private-transcendence-network
    driver: bridge
