[profile.default]
src = "src"
out = "out"
libs = ["lib"]

[rpc_endpoints]
avalancheFujiTestnet = "${AVALANCHE_FUJI_TESTNET_RPC_URL}"

[etherscan]
43113 = { key = "${SNOWTRACE_API_KEY}", url = "https://api.snowtrace.io/api" }

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
