# Using VScode extension REST Client (install it and click on 'Send Request' that appears above each request, separate requests with '###')

### USER

### Get all users from database
GET http://localhost:3000/users/ HTTP/1.1

### Get user by id
GET http://localhost:3000/users/<id> HTTP/1.1

### Create a new user
POST http://localhost:3000/users/create HTTP/1.1
content-type: application/json

{
	"username": "newUser3",
	"email": "newUser2@gmail.com",
	"password": "secure123441"
}

### Update user info (only username and/or email, for now)
PUT http://localhost:3000/users/<id> HTTP/1.1
content-type: application/json

{
	"data": {
		"username": "modified",
		"email": "modified@gmail.com"
	}
}

### Delete user from database
DELETE http://localhost:3000/users/<id> HTTP/1.1

### Login user and get a JWT token
POST http://localhost:3000/users/login HTTP/1.1
content-type: application/json

{
	"email": "test@gmail.com",
	"password": "secure123"
}

### PROFILE

### Get all profiles from database
GET http://localhost:3000/profiles/ HTTP/1.1

### Get profile by id
GET http://localhost:3000/profiles/<id> HTTP/1.1

### Update profile info (only name and/or bio, for now)
PUT http://localhost:3000/profiles/<id> HTTP/1.1
content-type: application/json

{
	"data": {
		"name": "modified",
		"bio": "I am the greatest!"
	}
}

### FRIEND

### Get all friends of a profile
GET http://localhost:3000/profiles/<id>/friends HTTP/1.1

### Add a friend to a profile
POST http://localhost:3000/friends/ HTTP/1.1
content-type: application/json

{
	"profileId": "f6d06da7-446e-4e1b-86a2-eb76db76279f",
	"friendId": "303a7e81-d2d2-471e-9571-6c25d3b5b7f6"
}
