# Using VScode extension REST Client (install it and click on 'Send Request' that appears above each request, separate requests with '###')

# Change 'http://localhost:3000/' to 'https://padaria.42.pt/api/' to test through Frontend container

### LEADERBOARD 

### Get user scores
GET http://localhost:3000/leaderboard/ HTTP/1.1