# Using VScode extension REST Client (install it and click on 'Send Request' that appears above each request, separate requests with '###')

### MATCH 

### Get all matches from a user
GET http://localhost:3000/matches/user/<id> HTTP/1.1

### Get a specific match
GET http://localhost:3000/matches/<id> HTTP/1.1
