# Using VScode extension REST Client (install it and click on 'Send Request' that appears above each request, separate requests with '###')

### PLAYER

### Get all players from database
GET http://localhost:3000/players/ HTTP/1.1

### Get player by id
GET http://localhost:3000/players/<id> HTTP/1.1

### Update player info (only name and/or bio, for now)
PATCH http://localhost:3000/players/<id> HTTP/1.1
content-type: application/json

{
	"name": "modified",
	"bio": "I am the greatest!"
}
