const avatarDefaultPicturePath = '../../../../static/avatar/default/';

export function getRandomAvatarPath() {
  const randomIndex = Math.floor(Math.random() * avatarImagePaths.length);
  return avatarImagePaths[randomIndex];
}

export const avatarImagePaths = [
  'bayonetta.png',
  'corrin.png',
  'dr_mario.png',
  'ice_climbers.png',
  'ken.png',
  'lucario.png',
  'mega_man.png',
  'olimar.png',
  'piranha_plant.png',
  'rob.png',
  'shulk.png',
  'wario.png',
  'zero_suit_samus.png',
  'bowser_jr.png',
  'daisy.png',
  'duck_hunt.png',
  'ike.png',
  'king_dedede.png',
  'lucas.png',
  'meta_knight.png',
  'pac_man.png',
  'pit.png',
  'rosalina_and_luma.png',
  'simon.png',
  'wii_fit_trainer.png',
  'bowser.png',
  'dark_pit.png',
  'falco.png',
  'incineroar.png',
  'king_k_rool.png',
  'lucina.png',
  'mewtwo.png',
  'palutena.png',
  'pokemon_trainer.png',
  'roy.png',
  'snake.png',
  'wolf.png',
  'captain_falcon.png',
  'dark_samus.png',
  'fox.png',
  'inkling.png',
  'kirby.png',
  'luigi.png',
  'mii_fighter.png',
  'peach.png',
  'richter.png',
  'ryu.png',
  'sonic.png',
  'yoshi.png',
  'chrom.png',
  'diddy_kong.png',
  'ganondorf.png',
  'isabelle.png',
  'link.png',
  'mario.png',
  'mr_game_and_watch.png',
  'pichu.png',
  'ridley.png',
  'samus.png',
  'toon_link.png',
  'young_link.png',
  'cloud.png',
  'donkey_kong.png',
  'greninja.png',
  'jigglypuff.png',
  'little_mac.png',
  'marth.png',
  'ness.png',
  'pikachu.png',
  'robin.png',
  'sheik.png',
  'villager.png',
  'zelda.png',
].map((fileName) => `${avatarDefaultPicturePath}${fileName}`);
